.gitignore, about/working-groups/index.md, about/working-groups/working-groups.json, serve.sh, theme/assets/js/working-groups.js, update_contributors.py
Adds a contributors section to the working groups page.
The `update_contributors.py` script adds contributors who aren't already in the `working-groups.json` file. This means anyone can raise a PR to add more details about themselves, i.e. full name, twitter, etc.
It also means people in the other groups aren't duplicated in the contributors section.
If this is an ok approach I'll probably set up a GitHub workflow that automatically runs this once a week. And if there are new contributors raise a PR automatically.
=> Add contributors to website

tool-center/tools.json
This tool generates SBOMs out of apt and optionally pip information.
Signed-off-by: Eliot Lear <lear@cisco.com>
=> add apt2sbom

about/supporters/index.md
We should also promote open source vendors. Multiple open-source vendors support CycloneDX.
=> Update Vendor Support

_data/tools.yml
* add tool `@cyclonedx/cyclonedx-library`
* removed the note regarding usage of `@cyclonedx/bom` as a library. - yes, it could be used as a lib, but it is a depricated feature i am planning to remove.
=> introduce tool: JavaScript library

capabilities/bomlink/index.md
Signed-off-by: Paul Horton <paul.horton@owasp.org>
=> fix: corrected link from `/capabilities/bomlink` to `/use-cases/#external-references`

theme/_includes/examples/external-references.html
The JSON did not validate as there were 2 missing commas between array entries in the "hashes" field.
=> Update external-references.html to fix JSON validation errors

_data/tools.yml
In particular:
- Trivially fix the name.
- Update the publisher (the GitHub project was transferred out of the "heremaps" org long ago).
- Capitalize "Open Source Software".
- Add the "transform" and "library" categories as ORT can programmatically transform SPDX to CycloneDX.
=> Update the entry to the ORT tool

_data/tools.yml
Update website URL for SCANOSS, which has migrated from `.co.uk` to `.com`
=> Update website for SCANOSS

_data/tools.yml
Remove analysis category for cyclonedx-npm-pipe tool, per agreement with author.
=> Remove analysis category for cyclonedx-npm-pipe tool

_data/tools.yml
This PR adds [Macaron](https://github.com/oracle/macaron), a  supply chain security analysis tool and policy engine that checks conformance to frameworks, such as SLSA. It integrates CycloneDX SBOM generator tools or takes an existing CycloneDX SBOM as input if available.
=> chore: add Macaron as a tool that supports CycloneDX SBOM

_data/carousel.yml, theme/_layouts/home.html
Sometimes, when viewing the CycloneDX.org webpage from a small-screen mobile device, the carousel has a split second where images do not load properly between slides. This update should resolve the issue.
=> Preload carousel images to increase responsiveness

_data/tools.yml
This adds an additional open source tool that can produce CycloneDX BOMs from a Rust Cargo project.  A standalone CLI tool, and GitHub Action is included.
I am not the author of the tool, just a happy user.
=> Add sbom-rs to tools list

use-cases/index.md
link to the web-=rendered version of the CycloneDX property taxonomy, where it is needed
=> docs: use case properties link to taxonomy

_data/tools.yml
The Rollup Plugin SBOM provides build integration tooling into [Rollup](https://rollupjs.org/) and [Vite](https://vitejs.dev/) frontend projects to generate SBOM's with packages shipped to production. It would be very nice to also get this tool listed on the official site.
**Repository**: https://github.com/janbiasi/rollup-plugin-sbom
**Package on NPM**: https://www.npmjs.com/package/rollup-plugin-sbom
=> Add rollup-plugin-sbom to the tools list for frontend projects

_data/tools.yml
The CycloneDX plugin for Conan was discontinued nine months ago in favor of the conan-extensions, which added support for CycloneDX in their tooling. The CycloneDX project was archived and documents this circumstance in the Readme. Therefore, I suggest this change to point interested parties directly to the recommended extensions without the hop over discontinued projects.
=> Update tools.yml for Conan

Gemfile, Gemfile.lock, _config.yml, theme/_includes/tool-card.html
- NEW: starts for GitHub-Gist
- based on: https://github.com/CycloneDX/cyclonedx.org/blob/26ff0be9ad9a40ac16ea677d3deab3f0ce345bbc/_data/tools.yml#L1952-L1959
- result:  
- NEW: forks and starts for GitLab-Repo:
- based on: https://github.com/CycloneDX/cyclonedx.org/blob/26ff0be9ad9a40ac16ea677d3deab3f0ce345bbc/_data/tools.yml#L1502-L1509
- result:  
- REFACTORED: forks and stars for GitHub-Repo
- based on: https://github.com/CycloneDX/cyclonedx.org/blob/26ff0be9ad9a40ac16ea677d3deab3f0ce345bbc/_data/tools.yml#L2-L10
- result:
=> tool-card: fork/stars for GitHub-gist & GitLab

_data/tools.yml
Meta Package Manager is a multi-platform CLI which allows you to export a SBOM of all packages installed on a system: https://kdeldycke.github.io/meta-package-manager/usecase.html#sbom-software-bill-of-materials
=> Add Meta Package Manager

guides/sbom/relationships.md
Clarify dependency graphs in the SBOM-guide.
as discussed in slack: https://cyclonedx.slack.com/archives/CVA0G10FN/p1704622629425539
:exclamation: this is in accordance with the guide: https://github.com/CycloneDX/guides/pull/21
=> sbom-guide: clarify relationship in CDX

theme/_layouts/examples.html, theme/_sass/components/_sections-list.scss
Fixes the issue outlined in #28
Also to make it more friendly I added some scrolling logic to keep the active element on the table in view.
I tried to apply the smooth scrolling though that seems to cause it to fail. While this could be achieved via Jquery I believe it would be more visually distracting to suddenly see another list scrolling smoothly rather than jumping to the right location, though it should be relatively easy to add should it be requested.
=> fix: sections scroll issue

_data/tools.yml
Add Cyberwatch vulnerability Manager.
Cyberwatch v14, now support CycloneDX 1.5 and 1.6
Documentation : https://docs.cyberwatch.fr/help/en/use_assets/use_asset_form/#sbom-file
=> Add Cyberwatch

_data/tools.yml
I made a new open-source visualization tool and I'd like it to be added to the official tools list. The tool is called Sunshine and is a SBOM visualization tool, with a sunburst chart and a table with components, vulnerabilities and licenses
=> Added Sunshine SBOM visualization tool
