index.md
=> Update MedScan URL

_config.yml
Please note: I couldn't get jekyll running locally. So I haven't actually tested this change.
=> Add slack to social list

about/working-groups/working-groups.json
No code commits but multiple issues logged for defects and enhancements in CLI, for example.
=> Addition of Mark Symons as Contributor

specification/overview/index.md
=> Add protocol buffers to list of supported formats

tool-center/tools.json
Addition of Cybellum's system as additional tool that generates SBOM and allows CycloneDX exports
Signed-off-by: boris-cybelllum <79354377+boris-cybelllum@users.noreply.github.com>
=> Added Cybellum to tools

about/working-groups/working-groups.json
Signed-off-by: Patrick Dwyer <patrick.dwyer@owasp.org>
=> Add Paul to maintainers

tool-center/tools.json
Hello!
I want to add a WordPress plugin to this list.
Thanks you
=> Add WpBom WordPress plugin

.well-known/security.txt, _config.yml
Signed-off-by: Patrick Dwyer <patrick.dwyer@owasp.org>
=> Add .well-known/security.txt

specification/overview/index.md
Signed-off-by: Sambhav Kothari <skothari44@bloomberg.net>
Fixes https://github.com/CycloneDX/specification/issues/100
=> Add conventional file names for storing CycloneDX BOM

tool-center/tools.json
Rebom is an open source SBOM catalog, project page: https://github.com/relizaio/rebom
Signed-off-by: Pavel Shukhman <taleodor@users.noreply.github.com>
=> Add Rebom to tools

capabilities/index.md
Signed-off-by: Paul Horton <paul.horton@owasp.org>
=> feat: called out BomLink directly in Capabilities page

tool-center/tools.json
Signed-off-by: Paul McKeown `<pmckeown at gmail.com>`
=> Add dependency track maven plugin to tools list

tool-center/tools.json
Signed-off-by: Christian Kotzbauer <git@ckotzbauer.de>
/cc @VinodAnandan
=> feat: add sbom-operator

docs/1.4/xml/index.html
Signed-off-by: Paul Horton <paul.horton@owasp.org>
=> doc: update XML 1.4 documentation for schema version 1.4.2

_data/tools.yml
https://github.com/CycloneDX/cyclonedx-node-npm 
is currently available via 
https://www.npmjs.com/package/%40cyclonedx/cyclonedx-npm
as a beta, that eventually will become final.
=> add tool `CycloneDX/cyclonedx-node-npm`

capabilities/saasbom/index.md
Resolve minor typo
Signed-off-by: Jordan Zebor <jzebor@gmail.com>
=> Fix typo in saasbom index.md

_data/supporters.yml
Signed-off-by: Patrick Dwyer <patrick.dwyer@owasp.org>
=> Add Fortress and Kondukto as supporters

_data/tools.yml
multiple times people tried to reinvent the wheel and asked about CDX spec and how to implment merging, signing, and other features.
Fortunately, these features are already implemented in the tools from @coderpatros . But i found the description in CDX tool center were lacking the information about all its beautiful features. 
SO i added more docs to help people find the existing tool for their use cases.
=> more description for "CycloneDX CLI" & "CycloneDX Web Tool"

_data/tools.yml
* Add `SBOMDiff` tool
* Add `bomber` tool
* Add `Covenant` tool
* Add category analysis for `CycloneDX CLI`
=> Add 3 tools and extra category for CycloneDX CLI

_data/tools.yml
Update tools with addition of repoUrl
* SBOMDiff
* bomber
* Covenant
=> Add repoUrl for 3 tools

_data/tools.yml
Signed-off-by: Marton ILLES <marton.illes@onekey.com>
=> Add ONEKEY firmware analysis to tools

_data/tools.yml
Add Request for Scribe Valint tool.
* Generation of CycloneDX SBOMS for container images, directories, files and SCM repositories.
* SBOM signing using InToto Attestations spec (SBOM predicate), sigstore keyless, KMS and X509 and TPM key based key supports.
* Supply chain integrity and policy based validation support.
* OCI, local and SaaS based SBOM storage and sharing.
Thanks
=> Scribe valint

_data/tools.yml
Signed-off-by: Aseem Jakhar <aseemjakhar@gmail.com>
=> Add EXPLIoT details

_data/tools.yml
Signed-off-by: Dmitry Raidman <dmitry@cybeats.com>
=> Update tool categories cybeats

_data/tools.yml
This PR is to add Sbomqs by interlynk-io to the tool center for CycloneDX. At interlynk we believe SBOM generation quality needs to improve, we would like to contribute a quality scoring mechanism for sboms, we hope this helps guide sbom generators & producers to up their game. 
@stevespringett we congratulate you on your 10 year journey with dependency track, and moving the industry forward. Appreciate it.
=> Add SBOM quality score tool

_data/tools.yml
=> Add Xygeni

_data/tools.yml
Deepbits released a toolset for SBOM building, vulnerability management, code intelligence, etc. 
This PR updates Deepbits link and description in Tool Center.
=> Update Deepbits tool link and description

_data/tools.yml
@stevespringett had a small typo in my previous PR.
=> Sbomgr github url typo fix

_data/tools.yml
Change publisher to OpenText and description to a better one.
=> Change publisher and description of Debricked

_data/supporters.yml, about/supporters/supporters.json
fixed failed linkage to adolus.svg file: no capital D
=> fix logo issue

_data/tools.yml
Signed-off-by: Mark Symons mark.symons@fujitsu.com
=> Add Snyk's Parlay Enrichment Tool

_data/tools.yml
Updated publisher, URLs, and description
Removed cdxgen-action
=> Update cdxgen details

_data/tools.yml
=> Add sbom-scorecard tool

guides/sbom/linking.md, theme/_includes/examples/assembly.html, theme/_includes/examples/authenticity.html, theme/_includes/examples/bom-link-bom.html, theme/_includes/examples/bom-link-vex.html, theme/_includes/examples/compositions.html, theme/_includes/examples/dependency-graph.html, theme/_includes/examples/external-references.html, theme/_includes/examples/integrity.html, theme/_includes/examples/inventory.html, theme/_includes/examples/license-compliance.html, theme/_includes/examples/openchain-conformance.html, theme/_includes/examples/outdated.html, theme/_includes/examples/packaging-distribution.html, theme/_includes/examples/pedigree.html, theme/_includes/examples/properties.html, theme/_includes/examples/provenance.html, theme/_includes/examples/security-advisories.html, theme/_includes/examples/security.html, theme/_includes/examples/services.html, theme/_includes/examples/vex.html, theme/_includes/examples/vulnerability-remediation.html
fixes #70
so that more people produce correct CDX documents with the support of their IDE
=> add schema to JSON examples

_data/carousel.yml
Following a review of the main page carousel wording, Kayla recommended a few changes in order to increase readability.
=> Update carousel wording for increased readability

_data/tools.yml
Added sbomasm - open source tool for assembling component SBOMs into product SBOM
=> [NO-TKT] Add sbomasm to cyclonedx tools

capabilities/bomlink/index.md, capabilities/bov/index.md, capabilities/hbom/index.md, capabilities/index.md, capabilities/mbom/index.md, capabilities/mlbom/index.md, capabilities/obom/index.md, capabilities/release-notes/index.md, capabilities/saasbom/index.md, capabilities/sbom/index.md, capabilities/vdr/index.md
=> link guide from capabilities

_data/tools.yml
We received a request from the creator of this tool to update some of the wording on their card in the tool center, so minor improvements have been made to the name and categories.
=> Update to SBOM Utility tool card

_data/tools.yml
=> Add Neo4Cyclone to Tools

_data/tools.yml
add SBOM.sh and SBOMcenter.io, remove retired CAS service
=> add SBOM.sh and SBOMcenter.io, remove retired CAS service

_data/carousel.yml, theme/_layouts/home.html
Updates:
- New carousel slide
- Updated Introduction text on the homepage
=> Add new carousel item and update introduction

_data/tools.yml
- Add Bitbucket Pipe sbom-utilities-pipe to list of tools
=> add sbom-utilities-pipe to tools list

_data/tools.yml
fixes https://github.com/CycloneDX/cyclonedx.org/issues/264
=> Buildroot tool URL corrected

about/working-groups/working-groups.json
Changing from my "web alias" to my real name.
=> Updating Michael Tsfoni (formerly Mike Zadik) in the working-groups.json

about/working-groups/working-groups.json
=> Update Olle E. Johansson presentation

_data/tools.yml
add bogrod command line tool to manage SBOM and VEX like source code
=> add bogrod command line tool to manage SBOM and VEX like source code

.github/workflows/pr_label_toolcenter.yml
=> chore: GH workflow label tool-center

_data/tools.yml
Add SettleTop's SBOM Vendor Management to the tools.yml file
=> Add SettleTop tooling to tools.yml

_data/tools.yml
=> add Threatrix to tool-center

_data/tools.yml
Add Sonar Cryptography Plugin and CBOM Viewer
=> Add CBOM tooling to CycloneDX Tool Center

_data/tools.yml
Add tools to tool center:
- CBOMkit
- CBOMkit-theia
=> Add additional CBOM tools to the tool center

schema/bom-1.6.proto, schema/bom-1.6.schema.json, schema/bom-1.6.xsd, specification/overview/index.md
- push updated CycloneDX 1.6.1 schema online -- were taken from tag 1.6.1
- link to 1.6.1 schema on github
docs were already published via #338
=> schema: 1.6.1
